### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by lionclaw** [Stereo101/python-MidiToVirtualPianoMacro#1]
Getting an error on opening pyMIDI.exe
![capture](https://cloud.githubusercontent.com/assets/22915554/24331567/ab190486-122e-11e7-88f9-67ccb2c5cf25.PNG)

**Comment by MinebloxGaming** [comment]
ye i have it how to fix it pls :(

**Comment by Stereo101** [comment]
Reading the error message, you are missing a common dll file.

See here for official installer from Microsoft

https://answers.microsoft.com/en-us/windows/forum/windows8_1-pictures-musicapp/api-ms-win-crt-runtime-l1-1-0dll-is-missing/b593b94e-6691-423b-a586-0b7f10131e35
