### ISSUE TITLE
Some songs not being shown in the "pyMIDI" file.

### ISSUE THREAD

**Issue by Talismanical** [Stereo101/python-MidiToVirtualPianoMacro#15]
Sometimes, some songs won't show up on that "pyMIDI" file, therefore it won't give me any selection to choosing it. Despite one of my songs being the exact same length and file size as some of my other songs, it will still not show up, is there any solution to this?

**Comment by Stereo101** [comment]
Check the file extension and change it so it ends in ".mid". Some midi files may end with ".midi" instead or it might be capitalized, and the program won't list that file.
