### ISSUE TITLE
Is there any way to hold the notes down?

### ISSUE THREAD

**Issue by Axarea** [Stereo101/python-MidiToVirtualPianoMacro#16]
I found a new virtual piano platform, and it has a way to manually sustain notes. Is there any way I can mess around with the code to make it detect when to press a certain note, and when to let go?

**Comment by Stereo101** [comment]
Yes it is possible, and it would require changes to the code. The source files are in the Source folder directly if you know a bit of python3 or would like to learn.

Is the sustain is done on a per note basis by holding the note down, or is it done through something like a piano sustain peddle where all notes played are sustained as long as the peddle is down? The Midi specification has both a notion of "Pedal" track events and key press / key release. The midi file you are using would of course need to have one of these modes of sustain encoded in the first place.

**Comment by Axarea** [comment]
It would be for each individual note, the easiest way to explain it would be the visual in synthesia, do those note sustains transfer over?

**Comment by Axarea** [comment]
I should also mention that I don't know python to the slightest, I've only learned a little bit of lua, and I'm not exactly sure what to even be looking for in this situation...

**Comment by Stereo101** [comment]
Information about held notes is now pulled from the midi file.
