### ISSUE TITLE
key pressed not able to be registered on games

### ISSUE THREAD

**Issue by sinomi13** [Stereo101/python-MidiToVirtualPianoMacro#17]
Some games that are not ran from a web-based platform, like Garry's mod, the keys pressed is not registering thus not allowing the program to play. 

edit: The keystrokes pressed does do actions on the game and even types in the chat, but when it comes to the piano itself, no sound nor keystroke is produced.
Garry's Mod Addon: https://steamcommunity.com/sharedfiles/filedetails/?id=104548572

**Comment by Stereo101** [comment]
Games often read user input in a less generalized way than a browser would for the sake of performance / reducing input lag. Getting key presses to register on a given game engine may require hooking the game or other case by case methods. Still, if anybody knows a simple and non-intrusive way to get key presses recognized in GMod/Source I'd be happy to add it in.

**Comment by Stereo101** [comment]
Same as #11
