### ISSUE TITLE
Keypress length

### ISSUE THREAD

**Issue by ManticoreV101** [Stereo101/python-MidiToVirtualPianoMacro#19]
So I was looking through a MIDI file using an editor and noticed that some notes are held rather than pressed. Can you make it so that it holds the key according to length of the note.

**Comment by Stereo101** [comment]
The update I made to the program last month that implemented this. As an example in song.txt you may have notes like this:
```
4.0 epI
5.997916666666667 ~e
5.997916666666667 ~p
6.0 wo
6.997916666666667 ~w
6.997916666666667 ~o
7.0 eQ
7.997916666666667 ~e
7.997916666666667 ~I
```
You can see from the first chord (epI), ep are released (~ preceding a note means release) while I is held much longer.

Do you have an example where the above isn't working?

**Comment by ManticoreV101** [comment]
Oh, sorry. I didn't check the new update. I downloaded the program again and it got the correct tempo for each key. Thanks :D
