### ISSUE TITLE
msvcr100.dll is missing

### ISSUE THREAD

**Issue by Choco1412** [Stereo101/python-MidiToVirtualPianoMacro#2]

**Comment by Mattyeet** [comment]
Is this safe?

**Comment by arletho** [comment]
https://www.dll-files.com/msvcr100.dll.html You have to download the .dll and put it inside the folder.

**Comment by Stereo101** [comment]
Its a bad idea to use dll's from random websites when you can get it from an official source instead.

The "msvcr" in the file name refers to "Microsoft Visual C++ Runtime". I would hazard a guess that running [Microsoft's Visual C++ runtime installer](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) would create the required dll for this.

**Comment by Sys-key-design** [comment]
It does not create the required dll
I don't seem to know what to do and I don't want to get any dll's from some other website

**Comment by Sys-key-design** [comment]
Ok so you need to download the x86 Microsoft Visual C++, the 2010 version.
Any other version didn't work for me.
My system is not even x84 so I don't know why it worked.

**Comment by Stereo101** [comment]
The x86 Microsoft Visual C++ 2010 creates the needed dll. This went unnoticed because this dll is a commonly installed by other software as a dependency.
