### ISSUE TITLE
pyMidi problem

### ISSUE THREAD

**Issue by 1u6ky** [Stereo101/python-MidiToVirtualPianoMacro#20]
So I have a lot of midi songs downloaded, but it went past Z which is the last letter so then I cant play the song that are past Z. Can you fix or help me with this problem?

**Comment by Stereo101** [comment]
I switched out numbers for letters on the file picker. I've also made it so you can directly drag/drop a midi file onto the executable to process it. You'll have to redownload, but it should be working.
