### ISSUE TITLE
Midi not reading after redacted

### ISSUE THREAD

**Issue by iamtermuxer** [Stereo101/python-MidiToVirtualPianoMacro#22]
But! It does working in other programs that read midi or something, what the problem might be?

**Comment by Stereo101** [comment]
Can you get me a link to the midi file?

**Comment by iamtermuxer** [comment]
It happens with every midi, but i will make it to the google drive gimme a sec

**Comment by iamtermuxer** [comment]
https://drive.google.com/file/d/1E5YjhOHgUX3Yd_vL5kj5za4VzdyCfehS/view?usp=sharing

**Comment by iamtermuxer** [comment]
Sorry idk how that works but when i downloaded it from drive it started working, i guess midi was just corrupter after editing, thank you for answering anyway
