### ISSUE TITLE
Tempo is not correct

### ISSUE THREAD

**Issue by manofmanytalents** [Stereo101/python-MidiToVirtualPianoMacro#3]
Trying to get this to work:
https://www.youtube.com/watch?v=Y9MtssSYHLc

Instead, I get a VERY fast song with a tempo of 322.

**Comment by itneveroccurred** [comment]
Old, but you just open song.txt in a notepad and set the number in the first line after tempo to the correct one.

**Comment by Stereo101** [comment]
I'm in the process of updating the program accommodate variable tempo, and it seems like I have this song working. Since this is redesign, it'll be a bit before I push this change.
