### ISSUE TITLE
The application was unable to start correctly 0xc00007b

### ISSUE THREAD

**Issue by arletho** [Stereo101/python-MidiToVirtualPianoMacro#4]
Can't open any of the 2 applications.

**Comment by itneveroccurred** [comment]
works fine for me, its on your side

**Comment by ClannishHalo** [comment]
any fix for this yet?

**Comment by arletho** [comment]
> any fix for this yet?

yeah i fixed this problem like one day after i posted the thread. i think you just have to install stuff needed for it to work, like windows stuff. search the same problem question in google for other apps, it's the same one.

**Comment by Stereo101** [comment]
install windows stuff
