### ISSUE TITLE
x86 Doesn't Work

### ISSUE THREAD

**Issue by kdoub05** [Stereo101/python-MidiToVirtualPianoMacro#40]
I was trying to run pyMIDI.exe and it said that my PC cant run it. Please help me. This happens even with the newest version of Python installed.
![Screenshot 2022-06-16 111702](https://user-images.githubusercontent.com/94686671/174117875-ed75d2db-961e-4288-a38b-6f61e55c60d0.png)

**Comment by Stereo101** [comment]
Your computer is 32bit and not 64bit?

**Comment by Stereo101** [comment]
You can try directly using the python files in the Source folder if you have python installed.

You need the keyboard library installed via pip, which should be "python -m pip install keyboard" in command prompt. If you don't have pip, or python isn't found in the command prompt, you can enable these options if you run the python installer again (tick install pip and add python to PATH).

You'll also need to move the midi files you want to use into the Source folder to work with them there.

The exe files are there so you don't have to do the above, but they might be compiled for 64bit only.

**Comment by kdoub05** [comment]
Thanks!
