### ISSUE TITLE
playSong executable problem

### ISSUE THREAD

**Issue by Studio404NotFound** [Stereo101/python-MidiToVirtualPianoMacro#51]
when I execute playsong for some reason it closes immediately after opening it.

**Comment by davidpho90** [comment]
yeah i have this problem on Win 11

**Comment by Raven13111** [comment]
If you are still having that problem, go to the folder and click the path then type "cmd" and "py playSong.py" then put the error here I'll try to fix it

**Comment by ZephyrWeiss** [comment]
> yeah i have this problem on Win 11

Oh I thought it was because I used Win 7 with Python 3.8 64

**Comment by Studio404NotFound** [comment]
![image_2023-11-25_204432314](https://github.com/Stereo101/python-MidiToVirtualPianoMacro/assets/150208334/d3365031-77c7-478c-aaa1-b5421a3df6ed)

**Comment by Raven13111** [comment]
Type pip install keyboard

**Comment by ZephyrWeiss** [comment]
> ![image_2023-11-25_204432314](https://private-user-images.githubusercontent.com/150208334/285629561-d3365031-77c7-478c-aaa1-b5421a3df6ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMTM0ODQsIm5iZiI6MTcwMTAxMzE4NCwicGF0aCI6Ii8xNTAyMDgzMzQvMjg1NjI5NTYxLWQzMzY1MDMxLTc3YzctNDc4Yy1hYWExLWI1NDIxYTNkZjZlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQxNTM5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzUxZjQyMDNhZDMyYWRkMWJkNjhjMjY2MmEwOGI5YjMzNzM1YTdhNGJlMzhhY2UyNmUwMzRmNzRiYTI1M2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hTfutzWuvBIRTKp3-C2BjjCZ8vIFFb1orQEjY9nVFFY)

Or install this in the folder (it worked for me): https://pypi.org/project/keyboard/

**Comment by Studio404NotFound** [comment]
Thanks

**Comment by Under031** [comment]
same error but "pip install keyboard" isn't working. any help?
