### ISSUE TITLE
Tempo is set to 0 when using another midi file that didn't come with installing.

### ISSUE THREAD

**Issue by 1001001zzz** [Stereo101/python-MidiToVirtualPianoMacro#7]
Whenever I download a midi file from the internet > do pymidi.exe > playsong.exe 
this happens 
![image](https://user-images.githubusercontent.com/54613473/63825982-b16f5000-c911-11e9-94ac-5c21090c9ed7.png)

**Comment by itneveroccurred** [comment]
You gotta edit song.txt and change the number after "tempo=" to the tempo of your midi file

**Comment by 1001001zzz** [comment]
> 
> 
> You gotta edit song.txt and change the number after "tempo=" to the tempo of your midi file, if you don't know it's tempo then download the musescore program and then you'll see it

I did that however it still says with the same thing as said above the reply. 
"Starting macro with offset t= 0.0"

**Comment by itneveroccurred** [comment]
I mean other than making sure you actually save the edit, I can only suggest redownloading this and see if that changes anything.

**Comment by Stereo101** [comment]
That "Starting macro with offset t= 0.0" is referring to the time at which the midi notes start, not the tempo of the song. This is because some midi files don't have notes at the start, so the offset skips forward to the first note.

Is the midi playing back fine?
