### ISSUE TITLE
scan codes

### ISSUE THREAD

**Issue by orlikmw** [Stereo101/python-MidiToVirtualPianoMacro#9]
how to replace clicks of your script with clicks using scan codes from this site https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-6.0/aa299374(v=vs.60)?redirectedfrom=MSDN

**Comment by Stereo101** [comment]
The keyboard scale is built into the script, but wouldn't be all to hard to change. Inside pyMIDI.py:
```
virtualPianoScale = "1!2@34$5%6^78*9(0qQwWeErtTyYuiIoOpPasSdDfgGhHjJklLzZxcCvVbBnm"
```
Changes mappings could be as easy as editing this string with some small gotchas for shifted keys.
